first-component
4cybersecurity/jetacademie-app pull request #8
Opened 2024-11-27 22:31 UTC by 4cybersecurity

2024-11-27 23:10 UTC, kod-man requested changes

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/Homepage.jsx
> +        <div>
Fragment diye bir olay var.  Eger div sadece parent ise, yani hic style yok ise eklemeye gerek yok.
<> code </> seklinde olabilir.

https://react.dev/reference/react/Fragment

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/MotivationSection/MotivationSection.jsx
> +import React, { useState, useEffect } from "react";
Dosyanin adi MotivationSection buyuk yazilmis. Mesela ayni HomePage folderi icinde info-section ise kucuk yazilmis.  Birini secelim oyle devam edelim

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/Navbar/Navbar.jsx
> +                    <li className="hover:bg-gray-100 px-4 py-2">
Cok tekrar eden kisimlar component olmali. Mesela li item burda ListItem adinda bir component olabilir. 

Grade 1, grade 2 gibi bilgiler ise arraydan gelir. ve map  methodu ile tekrar yaparsin

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/Navbar/Navbar.jsx
> +  );
Bu dosya 150 satir. Kucuk componentlar olusturabilriz.

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/info-section/InfoSection.jsx
> +Slider.propTypes = {
Bu cok guzel aslinda ama diger componentlarda yok nerdeyse hic. Ya hepsinde olsun ya hic olmasin

2024-11-27 23:10 UTC, kod-man commented on src/pages/HomePage/info-section/InfoSection.jsx
> +const Slider = ({ slides }) => {
Ayni sayfada iki tane component olmasin.

SliderComponent ve InfoSection iki component olsun. Import edilsin buraya

2024-11-27 23:10 UTC, kod-man commented on src/pages/DigitalLibraryPage/DigitalLibrary.jsx
> +            <Navbar />
Her sayfada navbar var. Her sayfaya ayri ayri koymak yerine  App.jsx dosyasina koyun. Biraz tricky ama siz yaparsiniz :)

2024-11-28 10:55 UTC, senesuzun commented on src/data/data.js
> +export default quotesData;
neye gerek yok anlamadim abi

2024-11-28 11:19 UTC, kod-man commented on src/data/data.js
> +export default quotesData;
son satirdaki export default ifadesine. zaten export ediyorsun yukarda

2024-12-01 19:43 UTC, kod-man requested changes

2024-12-01 19:43 UTC, kod-man commented on src/components/BookCard.jsx
> +    const colorPalettes = [
bu bir sabit ifade oldugu icin component disinda tutulmasi mantikli olur. Boylelikle component her render oldugunda bu ifadeyi yeniden olmusturmadigimiz icin performans kazanci saglariz.

2024-12-01 19:43 UTC, kod-man commented on src/components/BookCard.jsx
> +    const colors = colorPalettes[Math.floor(Math.random() * colorPalettes.length)];
Bu da sabit bir fonksiyon. Yani pure fonksiyon. Component disinda calculation yapilabilir.

Bence src/components icinde Bookcard folderi icinde utils.js diye bir dosya olusturup usttelo const ifadeyi ve bu fonksiyonu oraya tasiyabilirz

2024-12-02 16:11 UTC, kod-man approved these changes

2024-12-02 16:15 UTC, merged